SELECT DISTINCT A.NAME JOB_NAME,
				TO_CHAR(A.EFFECTIVE_START_DATE,'MM/DD/YYYY') EFFECTIVE_START_DATE,
				TO_CHAR(A.EFFECTIVE_END_DATE,'MM/DD/YYYY') EFFECTIVE_END_DATE,
				A.JOB_CODE,
				F.SET_CODE,
				DECODE(A.ACTIVE_STATUS,'A','ACTIVE','INACTIVE') STATUS,
				H.JOB_FAMILY_NAME,
				A.REGULAR_TEMPORARY,  
				A.FULL_PART_TIME
  
FROM    FUSION.PER_JOBS_F_VL A,
		FUSION.FND_SETID_SETS F,
		FUSION.HR_ORGANIZATION_V G,
		FUSION.PER_JOB_FAMILY_F_TL H
WHERE 1=1
AND A.SET_ID            =F.SET_ID (+)
AND A.BUSINESS_GROUP_ID = G.ORGANIZATION_ID
AND A.JOB_FAMILY_ID     =H.JOB_FAMILY_ID(+)
AND A.EFFECTIVE_START_DATE <= :eff_end_dt
AND H.EFFECTIVE_START_DATE <= :eff_end_dt
AND G.EFFECTIVE_START_DATE <= :eff_end_dt
order by A.NAME,EFFECTIVE_START_DATE



